username: GitHub Actions
icon_url: https://octodex.github.com/images/total-eclipse-of-the-octocat.jpg

title: "{{repositoryName}}"
title_link: "{{repositoryUrl}}"

text: "{{icon jobStatus}} - {{env.commit}} ({{ref}})"

fields:
  - title: Engine Version
    value: "{{env.ue_version}}"
    short: true
  - title: Target Platform
    value: "{{env.target_platform}}"
    short: true

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> - {{ref}}

colors:
  success: '#7DF591'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'